#!/usr/bin/env python3
# coding=utf-8

"""
Function for Square Progression
The function g(n) generates a string consisting only of opening parentheses '('.
"""
import math

def backfall(n: int) -> str:
    if n <= 0:
        return ""

    root = int(math.sqrt(n))
    return "(" * root

if __name__ == "__main__":
    print(backfall(0))
    print(backfall(1))
    print(backfall(4))
    print(backfall(9))
    print(backfall(12))


