#!/usr/bin/env python3
# coding=utf-8

"""
Function for Repeated Value
It will Return the Text how much time does user wants
"""

def repeat_str(text:str, num:int)->str:
    retval=" "
    while num > 0:
        retval=retval+text
        num = num-1
    return retval

